### ISSUE TITLE
ImageMagick モジュール参照状況について

### ISSUE THREAD

**Issue by cniikura** [movabletype/mt-plugin-shared-preview#16]
MovableTypeクラウド版が6月に予定しているアップデートにて「ImageMagickモジュール」を削除するそうですが、こちらの共有プレビュープラグインはImageMagickモジュールを参照している構造でしょうか。
画像調整と関わりないプラグインとは思いますが、念のためIssueを立てました。ご確認お願いいたします。

**Comment by usualoma** [comment]
このプラグインからはImageMagickへの依存はないので、モジュールの削除が動作に直接影響することはありません。
よろしくお願いします。

**Comment by cniikura** [comment]
ご返信ありがとうございます、了解しました。
