### ISSUE TITLE
MTクラウドについて

### ISSUE THREAD

**Issue by hoshi0208** [movabletype/mt-plugin-shared-preview#17]
mt-plugin-shared-previewを入れたところ、共有プレビューのリンクをは取得できるが、
見た目（CSSが適用されていない）が崩れている。
通常の「プレビュー」では問題なく表示できるため、解決策を知りたい。

**Comment by usualoma** [comment]
@hoshi0208 

SharedPreview プラグインについては、MovableTypeクラウドでも動作の実績はあり、クラウド版固有の問題というものはないと思います。

CSSが読み込まれない場合、CSSの指定が相対パスになっている可能性が高いと思います。

通常の「プレビュー」の場合には、ファイルとして書き出されてそれが表示されるため問題が起きにくいのですが、SharedPreview プラグインの場合には mt-shared-preview.cgi 内のiframeからの表示になりますので、CSSの指定は `/` から始まるルートからのパスにしていただいたり、 `mt:SiteURL` を使った絶対パスにしていただかないと読み込めないことがあります。

ご確認をお願いします。

**Comment by hoshi0208** [comment]
@usualoma 
ご回答ありがとうございます。
ご指摘通り絶対パスにしたところ、CSSが適用されました！
