### ISSUE TITLE
共有プレビューボタンを押した際に【Internal Server Error】になってしまう

### ISSUE THREAD

**Issue by nakamura-prart** [movabletype/mt-plugin-shared-preview#20]
共有プレビューボタンを押した際に【Internal Server Error】ページになり

ーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー
The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at [no address given] to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.
ーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー
と表示されてしまいます。
解決策はありますでしょうか？

**Comment by usualoma** [comment]
@nakamura-prart 返信が遅くなりました。すみません。

以下の点をご確認いただけますでしょうか。

* mt-shared-preview.cgi が、サーバー上の mt.cgi と同じ場所にアップロードされていること
* mt-shared-preview.cgi の実行権限が 755 になっていること
* セキュリティ上の設定により mt-shared-preview.cgi を実行できないような設定がされていないこと

よろしくお願いいたします。

**Comment by usualoma** [comment]
@nakamura-prart 時間が経過したので一度閉じさせていただきます。
また問題などありましたらご報告いただければ幸いです。
よろしくお願いします。
