### ISSUE TITLE
プラグインのバージョンについて

### ISSUE THREAD

**Issue by akaneha** [movabletype/mt-plugin-shared-preview#21]
Movable Type 7 r.5001を使用している時に「SharedPreview 0.2」をインストールし、使用していたのですが
バージョンを最新版のr.5301にアップグレードしたところ、動作しなくなってしまいました
今後プラグインの最新版リリースはありますでしょうか？

**Comment by usualoma** [comment]
@akaneha コメントありがとうございます。

r.5001からr.5301では、SharedPreviewの動作に影響のある変更はなく、SharedPreview 0.2 は r.5301 での動作もサポートしています。

MTのアップグレードの作業の中で、操作ミスでプラグインの一部のファイルのコピーが漏れてしまうようなケースもあるようですので、[インストール手順](https://github.com/movabletype/mt-plugin-shared-preview#%E3%82%A4%E3%83%B3%E3%82%B9%E3%83%88%E3%83%BC%E3%83%AB) をご確認いただき、再度ファイルをアップロードしてみていただけますでしょうか。

またそれでも解消しない場合には、どのような症状になっているか（ページを開いても表示されない、「共有プレビューで開く」のボタンやリンクが表示されない、など）具体的に情報をいただければもう少し確認できるポイントがあるかもしれません。

よろしくお願いします。

**Comment by akaneha** [comment]
プラグインの一部のファイルのコピーが漏れが原因でした！アップロードし直したところ正常に動作しました
ご返答ありがとうございました
