### ISSUE TITLE
リビジョンへの対応

### ISSUE THREAD

**Issue by naokikob** [movabletype/mt-plugin-shared-preview#22]
この共有プレビューは、リビジョン（CheckReleaseを用いています）には対応していないのでしょうか？
最新のリビジョンで「共有プレビューを開く」を選択すると本体ページのプレビューが生成されるようです。

**Comment by usualoma** [comment]
@naokikob 
はい、サーポートしているのはMovable Type本体の機能の範囲のみとなっております。

**Comment by naokikob** [comment]
ありがとうございます。今後もリビジョンに対応される予定はないということでしょうか？
共有プレビュー機能があると助かるのですが...

**Comment by usualoma** [comment]
ありがとうございます。

長期的な展望としては、Movable Type本体で公開状態のまま予約差し替えを行うことのできる機能の検討も行われており、そういった機能が実装された場合には、SharedPreview プラグインでも対応されるだろうと思われます。ただ差し替えの機能が実装される具体的な予定はないため、SharedPreview プラグインについても、予定されているという状況ではありません。

ただ、内部構造としてのリビジョンを利用する形で前述の機能が実装された場合にも、サードパーティの機能との互換性については保証されないものとなると思います。

現状としてはご期待に添えない形となってしまうかと存じます。申し訳ありません。ご要望として、今後の機能の実装の優先順位を考える上で参考にさせていただきます。
よろしくお願いいたします。

**Comment by naokikob** [comment]
了解しました。ご回答ありがとうございました。
