### ISSUE TITLE
SharedPreviewのヘッダーが100％表示、アイコンクリック時に処理が行えない

### ISSUE THREAD

**Issue by t-y-amamoto** [movabletype/mt-plugin-shared-preview#23]
MT7にプラグイン「SharedPreview」のインストールを行ったところ、以下の事象が発生しております。
①プレビューが見切れてしまっている
　ヘッダー部（アイコンが3つ表示されている箇所）がブラウザで100％表示となっており、
　その下にあるプレビューが画面表示の縮小を行わないと確認できない状態となっております
②アイコンが動作しない
　以下のアイコンをクリックしたところ、何も動作せず、プレビューリンク、パーマリンクの取得が行えない状態となっております。
　・共有プレビューリンクを取得
　・公開時のパーマリンクを取得
上記2件につきまして、解消方法をご教示頂けないでしょうか。

**Comment by t-y-amamoto** [comment]
@usualoma 
ご確認頂きありがとうございます。
> 他のサードパーティ製のプラグインを利用されている場合、サードパーティ製のプラグインを無効にした場合にも、事象が発生するかご確認いただけますでしょうか。
いくつかサードパーティ製のプラグインを使用しておりますが、別のプレビュー関連のプラグインを無効にしても事象は改善しませんでした。

・ダウンロードしたzipファイルを展開します。
・展開したフォルダの中の plugins > SharedPreview のフォルダを、サーバー上の plugins フォルダの中にアップロードします。
・次に mt-static > plugins > SharedPreview のフォルダを、サーバー上の mt-static > plugins のフォルダの中にアップロードします。
・最後に mt-shared-preview.cgi のファイルをアップロードします。
上記の通り構築を行っておりますが、何か他に必要な作業がございますでしょうか？

**Comment by usualoma** [comment]
@t-y-amamoto ご確認ありがとうございます。

インストールに関しては、記載していただいている他に必要な作業はありません。

プラグインについても情報ありがとうございます。
症状としては、「管理画面の書き換えやカスタマイズを行う機能をもつプラグイン」が、本来の影響範囲を超えて、SharedPreviewの画面に影響を与えているという可能性が高いと思います。「プレビュー関連のプラグイン」に限定せず、一度すべてのサードパーティ製のプラグインを無効にしてご確認をいただけますでしょうか。

よろしくお願いいたします。

**Comment by t-y-amamoto** [comment]
@usualoma 
ご確認頂きありがとうございます。
サードパーティ製のすべてのプラグインを無効にして確認しましたが、
「共有プレビューリンクを取得」「公開時のパーマリンクを取得」ともに動作しませんでした。
また、SixApart社様のプラグインにつきましても、「SharedPreview 0.2」以外すべて無効にして確認もしてみましたが、動作しませんでした。
引き続き、ご確認頂けますでしょうか。

**Comment by usualoma** [comment]
@t-y-amamoto 確認ありがとうございます。

これまでに、他のユーザーさんからは同様の症状の報告がないため、現状では原因の特定が難しいところになっております。

> ①の症状について、具体的にどのようになっているか分からないため、差し支えなければスクリーンショットをいただけますでしょうか。

こちらについてはご提供いただくことは難しいでしょうか。

> ①プレビューが見切れてしまっている
>　ヘッダー部（アイコンが3つ表示されている箇所）がブラウザで100％表示となっており、
>　その下にあるプレビューが画面表示の縮小を行わないと確認できない状態となっております

あるいは、上記の情報から想像するに、以下の画像ような状況かと想像しましたが、そのような状況でしょうか。

<img width="556" alt="preview-100" src="https://user-images.githubusercontent.com/30598/201611634-b72dba25-eeff-4804-9a86-316d73d7479f.png">


### その他の情報を教えてください

* Movable Type のバージョンを教えてください
* ご確認をいただいているウェブブラウザと、そのバージョンを教えてください
* 症状からは、JavaScriptのエラーが出ていることが予想されます。ウェブブラウザの開発者ツールを開き、GoogleChrome であればコンソールのタブでエラーが出ていないかご確認いだき、出ている場合には内容を教えてください。

<img width="981" alt="image" src="https://user-images.githubusercontent.com/30598/201612393-52e363d1-a1c7-4cce-9fcc-2f1450614823.png">

よろしくお願いします。

**Comment by usualoma** [comment]
@t-y-amamoto 

> ①プレビューが見切れてしまっている

この件については、あるいは以下のような表示でしょうか。
もしそうであれば、 mt-static/plugins/SharedPreview を正しくアップロードできていなかったり、あるいは、権限が 600 になっていてアクセスできないという状況が考えられます。
インストール先のMTのmt-staticの下に mt-static/plugins/SharedPreview という形でアップロードできていること、また権限についてはウェブサーバーが読み込みのできるものに設定されていることについて、ご確認をお願いします。

![image](https://user-images.githubusercontent.com/30598/201616916-0b918cf3-1970-4851-a54e-401b33fee328.png)

**Comment by t-y-amamoto** [comment]
@usualoma 
ご確認頂きありがとうございます。
各種情報につきまして、以下の通りご回答致します。

> ①プレビューが見切れてしまっている
⇒表示につきまして、ご連絡頂きました通りアイコンが縦に３つ並ぶ状態となっております。

> もしそうであれば、 mt-static/plugins/SharedPreview を正しくアップロードできていなかったり、あるいは、権限が 600 になっていてアクセスできないという状況が考えられます。
⇒「mt-static/plugins/SharedPreview」ですが、権限は777であたっており、
　また、SharedPreview配下の構成は以下となっております。
　/mt-static/plugins/SharedPreview
　┗css
　　┗mt.css
　　┗mt.css.map
　　┗mt.min.css
　　┗mt.min.css.map

> Movable Type のバージョンを教えてください
⇒「MT7 r.5201」となります。

> ご確認をいただいているウェブブラウザと、そのバージョンを教えてください
⇒Microsoft Edge 106.0.1370.42 IEモード　にて確認しております。

> 症状からは、JavaScriptのエラーが出ていることが予想されます。ウェブブラウザの開発者ツールを開き、GoogleChrome であればコンソールのタブでエラーが出ていないかご確認いだき、出ている場合には内容を教えてください。
⇒Chromeにて以下のエラーが検出されました。
Refused to apply style from 'http://xx.xx.xx.xx/mt/plugins/SharedPreview/css/mt.min.css?v=7.9.3' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

お手数ではございますが、ご確認の程よろしくお願い致します。

**Comment by usualoma** [comment]
@t-y-amamoto ありがとうございます。一番最後の、開発者ツールでのエラーが参考になりそうです。（以下、現状でも配慮していただいているかと思いますが、ホスト名やパスの情報については本番環境独自の情報がここで公開されてしまわないようお願いします。）

SharedPreview で読み込まれるCSSファイルのパスが、404などのエラーとなり、CSSでなくエラーページのHTMLが返されているため、上記のエラーが出ていそうです。

> http://xx.xx.xx.xx/mt/plugins/SharedPreview/css/mt.min.css?v=7.9.3

このURLの中の、ホストの直下の `/mt/` の部分が、加工していただいていないそのままの値だとしますと、 mt-config.cgi にて `StaticWebPath` を変更されていますでしょうか。
そのような運用の場合、インストール時に、 MTのインストールディレクトリの直下にある mt-static を、ウェブサーバーから参照可能な場所にコピーしたり、移動している場合があるかと思います。そういったケースでは、コピーしたり移動した先の mt-static/plugins/SharedPreview にファイルをアップロードしていただく必要があります。

また別の可能性として、権限については、「mt-static/plugins/SharedPreview」が777であっても、mt.min.cssが600のようになってしまっていて、403エラーとなっている可能性はあるかと思います。その場合にもコンソール上ではご提示いただいたエラーになります。その辺りの切り分けは、 `http://xx.xx.xx.xx/mt/plugins/SharedPreview/css/mt.min.css?v=7.9.3` を直接ウェブブラウザで開いていただくと、404なのか、403なのか、（あるいは 500系なのか）でもう少し判別できるかと思います。

よろしくお願いします。

**Comment by t-y-amamoto** [comment]
@usualoma 
ご確認頂きありがとうございます。
>「mt-static/plugins/SharedPreview」が777であっても、mt.min.cssが600のようになってしまっていて

申し訳ございません。記載に誤りがあり、SharedPreviewは「777」ではなく「600」です。
直接ウェブブラウザで開いてみたところ「404」エラーでした。

**Comment by usualoma** [comment]
@t-y-amamoto ありがとうございます。ではポイントを絞りましょう。

### mt-config.cgi で StaticWebPath を指定しているかどうか？

こちらはいかがでしょうか。

もし mt-config.cgi の内容が明らかでない場合には、MTの管理画面を開いていただいたときにも、以下のようにMT本体のパスも `/mt/` で始まるパスになっているかと思います。
```
<link rel="stylesheet" href="http://example.com/mt/css/mt.css?v=7.9.0" type="text/css" />
```

特に指定していなければ、
```
<link rel="stylesheet" href="http://example.com/mt/mt-static/css/mt.css?v=7.9.0" type="text/css" />
```

などのように mt-static が含まれるはずです。


### ファイルの権限

サーバー環境によりますが、特に設定にこだわりがない場合には、一般的には以下のようになっていると、トラブルは少ないかと思います。
* ディレクトリ（フォルダ） : 755
* ファイル :  644

ディレクトリ（フォルダ）の権限が 600 の場合にはその下の階層のファイルを読み込むことができません。（ただその権限設定だと、FTPでも下の階層が確認できないと思うので、実際には600ではないかもしれません）


### 対応するファイルが読み込めるようになること

まずは、 `http://xx.xx.xx.xx/mt/plugins/SharedPreview/css/mt.min.css` のURLで、SharedPreviewに含まれるファイルが参照されるように、適当な場所に適当な権限で設置していただく必要があるかと思います。そして前述の2点がそのための確認のポイントになるかと思います。これらはプラグインではなくサーバー側の設定の問題になりますので、その方面からのアプローチで解消を試みていただくのが早い解決につながると思います。

よろしくお願いします。

**Comment by usualoma** [comment]
@t-y-amamoto 状況をお伺いした範囲ではプラグイン側の問題ではないように思いますので、一度閉じさせていただきます。
まだ問題があるようでしたら、お気軽に再度開いてご連絡ください。
よろしくお願いします。
