### ISSUE TITLE
マルチドメインサイト構成時、外部CSSファイルが相対パス参照だとプレビューページにデザインがあたらない

### ISSUE THREAD

**Issue by acokikoy** [movabletype/mt-plugin-shared-preview#28]
一つのMTで、異なるドメインのサイトA、サイトBを運用しています。
MT本体はサイトA側にインストールされています（構成は、末尾に記載）。

サイトA（MTと同じドメイン）の方の共有プレビューは問題ないのですが、
ドメインBの方で共有プレビューすると、デザインがあたらない状態でプレビューされてしまいます。

外部CSSの読み込みは 次のようにドキュメントルートからの相対パスで記述しています。
`<link rel="stylesheet" href="/css/style.css">`

どうやら、共有プレビュー時、ドメインA側の/css/style.cssを見に行って失敗しているようです。
絶対パスで、`href="https://ドメインB/css/style.css"` 式に記述すれば解決すると思いますが、
一般公開用のドメインが異なる（S3配信して公開する）都合で、絶対パスでの記述は避けたい事情があります。

こういった場合、よき解決方法はございますでしょうか？

※参考までに、MT本体とサイトA,Bの関係は以下のような感じで、
 同じサーバ上にvhostsで分かれて入っています。MT本体はサイトA側のcgi-binにインストールしています。

【MT本体】
https://ドメインA/cgi-bin/mt/mt.cgi
/var/www/vhosts/AAA/cgi-bin/mt
/var/www/vhosts/AAA/public_html/mt-static

【サイトA】
https://ドメインA/
/var/www/vhosts/AAA/public_html

【サイトB】 ← こっちのプレビューでデザインがあたらない
https://ドメインB/
/var/www/vhosts/BBB/public_html

**Comment by usualoma** [comment]
@acokikoy 
お問い合わせありがとうございます。

共有プレビューの表示時には、 `preview_template` という真偽値の変数が真になりますので、これを利用してCSSを出し分けていただく方法があると思います。たとえば以下のように書くことができます。

```mtml
<mt:If name="preview_template">
<link rel="stylesheet" href="https://ドメインB/css/style.css" />
<mt:Else>
<link rel="stylesheet" href="/css/style.css" />
</mt:If>
```

あるいは[base](https://developer.mozilla.org/ja/docs/Web/HTML/Element/base)要素を使って文書全体の相対パスの参照元を変更することもできます。

```mtml
<mt:If name="preview_template">
<base href="https://ドメインB/" >
</mt:If>
```

ご確認いただけますでしょうか。
よろしくお願いします。

**Comment by acokikoy** [comment]
早速のご回答ありがとうございます。
base要素の方で対応してみようと思います。
